# file: 	Makefile
# athor:	Ryan Reece  <ryan.reece@cern.ch>
# created: 	February 2010
#------------------------------------------------------------------------------

# Package information
LIBRARY = D3PDObjects
OBJDIR  = obj
DEPDIR  = $(OBJDIR)/dep
SRCDIR  = src
INCDIR  = include

# Include the generic compilation rules
include $(SFRAME_DIR)/Makefile.common

