# file: 	Makefile
# athor:	Ryan Reece  <ryan.reece@cern.ch>
# created: 	February 2010
#------------------------------------------------------------------------------

# Package information
LIBRARY = AtlasSFrameUtils
OBJDIR  = obj
DEPDIR  = $(OBJDIR)/dep
SRCDIR  = src
INCDIR  = include

# additional include paths
INCLUDES += -I../D3PDObjects/include
INCLUDES += -I../CommonTools/include
INCLUDES += -I../RootCore/RootCore/include

# Include the generic compilation rules
include $(SFRAME_DIR)/Makefile.common

