import os
#from dataSets import data12_electrons_hsg2_test as datasets
#from dataSets import data12_electrons_hsg2 as datasets
#from dataSets import data12_muons_hsg2 as datasets
#from dataSets import mc12_hsg2 as datasets
#from dataSets import data12_electrons_hsg2_tp as datasets
#from dataSets import data12_muons_hsg2_tp as datasets
#from dataSets import mc12_ttbar as datasets
#from dataSets import mc12_egamma as datasets
#from dataSets import mc12_higgs as datasets
#from dataSets import data12_muons_hsg2_2l as datasets
#from dataSets import mc12_TPG as datasets
from dataSets import data12_TPG as datasets


preFix = "user.sheim."
tag = ".2"
postFix = ".skim/"

#outputfilename = "skim_2l.root"
outputfilename = "skim_tpg.root"
filetype="data"
#filetype="mc"
treename="physics"
#treename="egamma"
#runscript="python skim2l.py $1 \"" + filetype + "\" \"" + treename + "\" \"" + outputfilename + "\""
runscript="python skim_TPG.py $1 \"" + filetype + "\" \"" + treename + "\" \"" + outputfilename + "\""

f = open('runSkims.sh', 'w')
print >>f, "#!/bin/bash"
#print >>f, ""
print >>f, "#This file is generated by submitSkims2Grid.py"
print >>f, "echo \"arguments were:\""
print >>f, "echo \"outputfilename: ", outputfilename, "\""
print >>f, "echo \"filetype: ", filetype, "\""
print >>f, "echo \"treename: ", treename, "\""
print >>f, "source setEx.sh"
print >>f, "cd externals/egammaAnalysisUtils/cmt"
print >>f, "make -f Makefile.Standalone"
print >>f, "cd -"
print >>f, "ln -s externals/egammaAnalysisUtils/StandAlone/egammaAnalysisUtils.so ."
print >>f, runscript

f.close()

os.system("chmod +x runSkims.sh")

#exit(0)

f_doc = open('submitted_'+tag+'.txt', 'w')

for i in range(len(datasets)):
    
    print 'Submitting dataset: ' + str(i+1) + '/' + str(len(datasets))
    
    command = "prun "
    command += " --exec \"bash runSkims.sh %IN\""
    #command += " --nGBPerJob=MAX"

    command += " --nFilesPerJob=2"
    #command += " --nFiles=1"

    command += " --inDS "+datasets[i]
    dsName = datasets[i].rstrip("/")
    command += " --outDS "+preFix+dsName[:110]+tag+postFix
    #command += " --outDS "+preFix+dsName+tag+postFix

    #command += " --athenaTag=17.0.6" #to set up ROOT
    command += " --athenaTag=17.2.4"
 

    #command += " --excludedSite=ANALY_MPPMU,ANALY_ROMANIA07,ANALY_LAPP,ANALY_ARC,ANALY_LIV,ANALY_INFN-MILANO-ATLASC,ANALY_MANC,ANALY_IN2P3-CC,ANALY_RAL_XROOTD,ANALY_RAL"
    command += " --excludedSite=ANALY_OX,ANALY_SARA"   


    command += " --outputs "+outputfilename

    #command += " --destSE=UPENN_LOCALGROUPDISK" ###sends output directly to tier3
    
    #command += " --mergeOutput"
    
    #command += " --nFiles=1"  #for testing

    ####
    print command
    os.system(command)

    print >>f_doc, preFix+dsName[:110]+tag+postFix


