// Dear emacs, this is -*- c++ -*-
// -------------------------------------------------------------
//             Code produced by D3PDMakerReader
//
//  author: Attila Krasznahorkay <Attila.Krasznahorkay@cern.ch>
// -------------------------------------------------------------
#ifndef D3PDREADER_PhotonD3PDObject_H
#define D3PDREADER_PhotonD3PDObject_H

#include <map>
#include <vector>
using std::vector;

#include <TObject.h>
#include <TString.h>

#include "D3PDObjectBase.h"
#include "D3PDReadStats.h"
#include "VarHandle.h"
#include "VarProxy.h"

class TTree;

namespace D3PDReader {

   // Forward declaration(s):
   class PhotonD3PDObject;

   /**
    * Code generated by CodeGenerator_v2 on:
    *  host = pc-penn-d-01
    *  OS   = Linux / 2.6.18-308.8.2.el5
    *  user = stahlman
    *  time = Fri Jun 29 14:28:44 2012
    */
   class PhotonD3PDObjectElement : public TObject {

      friend class PhotonD3PDObject;

   protected:
      /// Constructor only visible to PhotonD3PDObject
      PhotonD3PDObjectElement( size_t index, const PhotonD3PDObject& parent );

   public:
      /// Copy constructor
      PhotonD3PDObjectElement( const PhotonD3PDObjectElement& parent );

      /// Parent object of this proxy object
      const PhotonD3PDObject* GetParent() const;
      /// Index of the object inside its container
      size_t GetIndex() const;

      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_CaloPointing_eta] 
      VarProxy< float > CaloPointing_eta;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_CaloPointing_sigma_eta] 
      VarProxy< float > CaloPointing_sigma_eta;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_CaloPointing_sigma_zvertex] 
      VarProxy< float > CaloPointing_sigma_zvertex;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_CaloPointing_zvertex] 
      VarProxy< float > CaloPointing_zvertex;
      VarProxy< float > E;
      /// [detail 5]
      VarProxy< float > E033;
      /// [detail 7]
      VarProxy< float > E1152;
      /// [detail 6]
      VarProxy< float > E132;
      /// [detail 15]
      VarProxy< float > E233;
      /// [detail 18]
      VarProxy< float > E237;
      /// [detail 19]
      VarProxy< float > E277;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_ED_Njets] 
      VarProxy< float > ED_Njets;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_ED_median] 
      VarProxy< float > ED_median;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_ED_sigma] 
      VarProxy< float > ED_sigma;
      /// DeltaR between the offline and trigger objects.
      VarProxy< float > EF_dr;
      /// Index in trig_EF_ph_
      VarProxy< int > EF_index;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_ES0_real] 
      VarProxy< float > ES0_real;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_ES1_real] 
      VarProxy< float > ES1_real;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_ES2_real] 
      VarProxy< float > ES2_real;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_ES3_real] 
      VarProxy< float > ES3_real;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_EcellS0] 
      VarProxy< float > EcellS0;
      /// [detail 27]
      VarProxy< float > Emax2;
      /// [detail 38]
      VarProxy< float > Emins1;
      VarProxy< float > Es0;
      VarProxy< float > Es1;
      VarProxy< float > Es2;
      VarProxy< float > Es3;
      VarProxy< float > Et;
      /// [detail 285]
      VarProxy< float > Etcone15;
      /// [detail 299]pt-corrected isolation energy within DR=0.15 cone
      VarProxy< float > Etcone15_pt_corrected;
      /// [detail 1]
      VarProxy< float > Etcone20;
      /// [detail 300]pt-corrected isolation energy within DR=0.20 cone
      VarProxy< float > Etcone20_pt_corrected;
      /// [detail 286]
      VarProxy< float > Etcone25;
      /// [detail 301]pt-corrected isolation energy within DR=0.25 cone
      VarProxy< float > Etcone25_pt_corrected;
      /// [detail 2]
      VarProxy< float > Etcone30;
      /// [detail 302]pt-corrected isolation energy within DR=0.30 cone
      VarProxy< float > Etcone30_pt_corrected;
      /// [detail 287]
      VarProxy< float > Etcone35;
      /// [detail 303]pt-corrected isolation energy within DR=0.35 cone
      VarProxy< float > Etcone35_pt_corrected;
      /// [detail 3]
      VarProxy< float > Etcone40;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_Etcone40_ED_corrected] 
      VarProxy< float > Etcone40_ED_corrected;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_Etcone40_corrected] 
      VarProxy< float > Etcone40_corrected;
      /// [detail 304]pt-corrected isolation energy within DR=0.40 cone
      VarProxy< float > Etcone40_pt_corrected;
      /// [detail 0]
      VarProxy< float > Etcone45;
      /// [detail 9]
      VarProxy< float > Ethad;
      /// [detail 8]
      VarProxy< float > Ethad1;
      /// [detail 170]
      VarProxy< float > EtringnoisedR03sig2;
      /// [detail 171]
      VarProxy< float > EtringnoisedR03sig3;
      /// [detail 172]
      VarProxy< float > EtringnoisedR03sig4;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_HPV_eta] 
      VarProxy< float > HPV_eta;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_HPV_sigma_eta] 
      VarProxy< float > HPV_sigma_eta;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_HPV_sigma_zvertex] 
      VarProxy< float > HPV_sigma_zvertex;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_HPV_zvertex] 
      VarProxy< float > HPV_zvertex;
      VarProxy< double > Hmatrix;
      VarProxy< double > Hmatrix5;
      /// DeltaR between the offline and trigger objects.
      VarProxy< float > L1_dr;
      /// Index in trig_L1_emtau_
      VarProxy< int > L1_index;
      /// DeltaR between the offline and trigger objects.
      VarProxy< float > L2_dr;
      /// Index in trig_L2_ph_
      VarProxy< int > L2_index;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_NN_discriminant] 
      VarProxy< float > NN_discriminant;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_NN_passes] 
      VarProxy< int > NN_passes;
      VarProxy< unsigned int > OQ;
      VarProxy< float > Rconv;
      VarProxy< double > adaboost;
      VarProxy< int > author;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_calibHitsShowerDepth] Shower depth as defined by the calib hits cluster correction
      VarProxy< float > calibHitsShowerDepth;
      VarProxy< float > cl_E;
      VarProxy< float > cl_eta;
      VarProxy< float > cl_phi;
      VarProxy< float > cl_pt;
      /// Number of tracks for the first conversion candidate; 0 if no conversion or if there are more than two tracks.
      VarProxy< int > convFlag;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_convIP] 
      VarProxy< float > convIP;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_convIPRev] 
      VarProxy< float > convIPRev;
      /// [detail 265]
      VarProxy< float > convMatchDeltaEta1;
      /// [detail 267]
      VarProxy< float > convMatchDeltaEta2;
      /// [detail 266]
      VarProxy< float > convMatchDeltaPhi1;
      /// [detail 268]
      VarProxy< float > convMatchDeltaPhi2;
      /// [detail 72]
      VarProxy< float > convanglematch;
      /// [detail 71]
      VarProxy< float > convtrackmatch;
      VarProxy< int > convtrk1nBLHits;
      VarProxy< int > convtrk1nPixHits;
      VarProxy< int > convtrk1nSCTHits;
      VarProxy< int > convtrk1nTRTHits;
      VarProxy< int > convtrk2nBLHits;
      VarProxy< int > convtrk2nPixHits;
      VarProxy< int > convtrk2nSCTHits;
      VarProxy< int > convtrk2nTRTHits;
      VarProxy< float > convvtxchi2;
      VarProxy< float > convvtxx;
      VarProxy< float > convvtxy;
      VarProxy< float > convvtxz;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_deltaEmax2] 
      VarProxy< float > deltaEmax2;
      VarProxy< float > deltaEs;
      /// [detail 76]
      VarProxy< float > depth;
      /// Index in el_
      VarProxy< int > el_index;
      /// [detail 39]
      VarProxy< float > emaxs1;
      /// [detail 74]
      VarProxy< float > errz;
      VarProxy< float > eta;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_etacellS0] 
      VarProxy< float > etacellS0;
      /// [detail 75]
      VarProxy< float > etap;
      VarProxy< float > etas0;
      VarProxy< float > etas1;
      VarProxy< float > etas2;
      VarProxy< float > etas3;
      /// [detail 11]
      VarProxy< float > f1;
      /// [detail 13]
      VarProxy< float > f1core;
      /// [detail 12]
      VarProxy< float > f3;
      /// [detail 14]
      VarProxy< float > f3core;
      /// [detail 28]
      VarProxy< float > fside;
      VarProxy< int > goodOQ;
      VarProxy< int > hasconv;
      /// True if the first conversion candidate has 1 or 2 tracks.
      VarProxy< int > isConv;
      /// IsEM mask --- bits are set for each cut that FAILS.
      VarProxy< unsigned int > isEM;
      /// Loose IsEM mask --- bits are set for each cut that FAILS.
      VarProxy< unsigned int > isEMLoose;
      /// Medium IsEM mask --- bits are set for each cut that FAILS.
      VarProxy< unsigned int > isEMMedium;
      /// Tight IsEM mask --- bits are set for each cut that FAILS.
      VarProxy< unsigned int > isEMTight;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_isIso] Mask of isolation cuts that this object fails.  Bits are defined in egammaInterfaces/egammaIsolationMVATopToolsDefs.h,or from python, in ROOT.egammaIsolationType (in egammaInterfacesEnumsDict).
      VarProxy< unsigned int > isIso;
      VarProxy< int > isRecovered;
      VarProxy< double > isolationlikelihoodhqelectrons;
      VarProxy< double > isolationlikelihoodjets;
      VarProxy< float > jet_E;
      VarProxy< float > jet_dr;
      VarProxy< float > jet_eta;
      VarProxy< float > jet_m;
      VarProxy< int > jet_matched;
      VarProxy< float > jet_phi;
      VarProxy< float > jet_pt;
      VarProxy< float > jet_truth_E;
      VarProxy< float > jet_truth_dr;
      VarProxy< float > jet_truth_eta;
      VarProxy< float > jet_truth_m;
      VarProxy< int > jet_truth_matched;
      VarProxy< float > jet_truth_phi;
      VarProxy< float > jet_truth_pt;
      VarProxy< double > loglikelihood;
      VarProxy< int > loose;
      VarProxy< int > looseAR;
      VarProxy< int > looseARIso;
      VarProxy< int > looseIso;
      VarProxy< float > m;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_mvaptcone20] Sum of track transverse momenta within a cone of radius 0.2, as calculated by the egammaIsolationMVATopTool
      VarProxy< float > mvaptcone20;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_mvaptcone30] Sum of track transverse momenta within a cone of radius 0.3, as calculated by the egammaIsolationMVATopTool
      VarProxy< float > mvaptcone30;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_mvaptcone40] Sum of track transverse momenta within a cone of radius 0.4, as calculated by the egammaIsolationMVATopTool
      VarProxy< float > mvaptcone40;
      /// Number of conversion vertices.
      VarProxy< int > nConv;
      /// Number of conversion vertices with exactly two tracks.
      VarProxy< int > nDoubleTrackConv;
      /// Number of conversion vertices with exactly one track.
      VarProxy< int > nSingleTrackConv;
      VarProxy< double > neuralnet;
      /// [detail 295]
      VarProxy< float > nucone20;
      /// [detail 296]
      VarProxy< float > nucone30;
      /// [detail 297]
      VarProxy< float > nucone40;
      /// MC particle origin, from classifier tool.
      VarProxy< int > origin;
      VarProxy< float > phi;
      VarProxy< float > phis0;
      VarProxy< float > phis1;
      VarProxy< float > phis2;
      VarProxy< float > phis3;
      VarProxy< double > photonbgweight;
      VarProxy< double > photonweight;
      VarProxy< float > pt;
      VarProxy< float > pt1conv;
      VarProxy< float > pt2conv;
      /// [detail 293]
      VarProxy< float > ptcone20;
      /// [detail 241]
      VarProxy< float > ptcone30;
      /// [detail 294]
      VarProxy< float > ptcone40;
      VarProxy< float > ptconv;
      VarProxy< float > px;
      VarProxy< float > py;
      VarProxy< float > pz;
      VarProxy< float > pzconv;
      VarProxy< float > rawcl_E;
      VarProxy< float > rawcl_Es0;
      VarProxy< float > rawcl_Es1;
      VarProxy< float > rawcl_Es2;
      VarProxy< float > rawcl_Es3;
      VarProxy< double > cl_etaCalo;
      VarProxy< double > cl_phiCalo;
      VarProxy< float > rawcl_eta;
      VarProxy< float > rawcl_etas0;
      VarProxy< float > rawcl_etas1;
      VarProxy< float > rawcl_etas2;
      VarProxy< float > rawcl_etas3;
      VarProxy< float > rawcl_phi;
      VarProxy< float > rawcl_phis0;
      VarProxy< float > rawcl_phis1;
      VarProxy< float > rawcl_phis2;
      VarProxy< float > rawcl_phis3;
      VarProxy< float > rawcl_pt;
      VarProxy< float > reta;
      VarProxy< double > ringernn;
      VarProxy< std::vector<float,std::allocator<float> > > rings_E;
      VarProxy< float > rphi;
      /// [detail 40]
      VarProxy< float > rphiallcalo;
      VarProxy< int > tight;
      VarProxy< int > tightAR;
      VarProxy< int > tightARIso;
      VarProxy< int > tightIso;
      VarProxy< float > topoEMdr;
      VarProxy< float > topoEMeta;
      VarProxy< int > topoEMmatched;
      VarProxy< float > topoEMphi;
      VarProxy< float > topoEMpt;
      /// [detail 306]
      VarProxy< float > topoEtcone20;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_topoEtcone20_corrected] 
      VarProxy< float > topoEtcone20_corrected;
      /// [detail 307]
      VarProxy< float > topoEtcone30;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_topoEtcone30_corrected] 
      VarProxy< float > topoEtcone30_corrected;
      /// [detail 308]
      VarProxy< float > topoEtcone40;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_topoEtcone40_corrected] 
      VarProxy< float > topoEtcone40_corrected;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_topoEtcone60] 
      VarProxy< float > topoEtcone60;
      VarProxy< float > topodr;
      VarProxy< float > topoeta;
      VarProxy< int > topomatched;
      VarProxy< float > topophi;
      VarProxy< float > topopt;
      VarProxy< float > truth_E;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_truth_Rconv] 
      VarProxy< float > truth_Rconv;
      VarProxy< int > truth_barcode;
      VarProxy< float > truth_deltaRRecPhoton;
      VarProxy< float > truth_eta;
      /// Index in mc_
      VarProxy< int > truth_index;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_truth_isBrem] 
      VarProxy< int > truth_isBrem;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_truth_isConv] 
      VarProxy< int > truth_isConv;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_truth_isFromHardProc] 
      VarProxy< int > truth_isFromHardProc;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_truth_isPhotonFromHardProc] 
      VarProxy< int > truth_isPhotonFromHardProc;
      VarProxy< int > truth_matched;
      VarProxy< int > truth_motherbarcode;
      VarProxy< int > truth_mothertype;
      VarProxy< float > truth_phi;
      VarProxy< float > truth_pt;
      VarProxy< int > truth_status;
      VarProxy< int > truth_type;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_truth_zconv] 
      VarProxy< float > truth_zconv;
      /// MC particle type, from classifier tool.
      VarProxy< int > type;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_Chi2] 
      VarProxy< std::vector<float,std::allocator<float> > > vx_Chi2;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_DR1R2] 
      VarProxy< std::vector<float,std::allocator<float> > > vx_DR1R2;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_Dcottheta] 
      VarProxy< std::vector<float,std::allocator<float> > > vx_Dcottheta;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_Dist] 
      VarProxy< std::vector<float,std::allocator<float> > > vx_Dist;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_Dphi] 
      VarProxy< std::vector<float,std::allocator<float> > > vx_Dphi;
      VarProxy< std::vector<float,std::allocator<float> > > vx_E;
      VarProxy< std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > > > vx_convTrk_TRTHighTHitsRatio;
      VarProxy< std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > > > vx_convTrk_TRTHighTOutliersRatio;
      VarProxy< std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > > > vx_convTrk_chi2;
      VarProxy< std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > > > vx_convTrk_eProbabilityBrem;
      VarProxy< std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > > > vx_convTrk_eProbabilityComb;
      VarProxy< std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > > > vx_convTrk_eProbabilityHT;
      VarProxy< std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > > > vx_convTrk_eProbabilityToT;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_expectBLayerHit;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_fitter;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_hitPattern;
      /// Number of ntuple rows.
      VarProxy< std::vector<int,std::allocator<int> > > vx_convTrk_n;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nBLHits;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nBLSharedHits;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nBLayerOutliers;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nBLayerSplitHits;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nCSCEtaHits;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nCSCPhiHits;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nContribPixelLayers;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nCscEtaHoles;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nCscPhiHoles;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nGangedFlaggedFakes;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nGangedPixels;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nHits;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nHoles;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nMDTHits;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nMdtHoles;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nOutliersOnTrack;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nPixHits;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nPixHoles;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nPixSharedHits;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nPixSplitHits;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nPixelDeadSensors;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nPixelOutliers;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nPixelSpoiltHits;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nRPCEtaHits;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nRPCPhiHits;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nRpcEtaHoles;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nRpcPhiHoles;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nSCTDeadSensors;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nSCTDoubleHoles;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nSCTHits;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nSCTHoles;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nSCTOutliers;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nSCTSharedHits;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nSCTSpoiltHits;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nSiHits;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nTGCEtaHits;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nTGCPhiHits;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nTRTDeadStraws;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nTRTHighTHits;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nTRTHighTOutliers;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nTRTHits;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nTRTHoles;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nTRTOutliers;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nTRTTubeHits;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nTgcEtaHoles;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_nTgcPhiHoles;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_ndof;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_particleHypothesis;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_patternReco1;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_patternReco2;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_standardDeviationOfChi2OS;
      VarProxy< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > vx_convTrk_trackProperties;
      VarProxy< std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > > > vx_convTrk_weight;
      VarProxy< std::vector<float,std::allocator<float> > > vx_m;
      /// Number of ntuple rows.
      VarProxy< int > vx_n;
      VarProxy< std::vector<int,std::allocator<int> > > vx_nTracks;
      VarProxy< std::vector<float,std::allocator<float> > > vx_px;
      VarProxy< std::vector<float,std::allocator<float> > > vx_py;
      VarProxy< std::vector<float,std::allocator<float> > > vx_pz;
      VarProxy< std::vector<float,std::allocator<float> > > vx_sumPt;
      VarProxy< std::vector<float,std::allocator<float> > > vx_x;
      VarProxy< std::vector<float,std::allocator<float> > > vx_y;
      VarProxy< std::vector<float,std::allocator<float> > > vx_z;
      /// [detail 25]
      VarProxy< float > weta2;
      /// [detail 24]
      VarProxy< float > ws3;
      /// [detail 37]
      VarProxy< float > wstot;
      VarProxy< float > zconv;
      /// [detail 73]
      VarProxy< float > zvertex;

   private:
      /// Reference to the parent of this object
      const PhotonD3PDObject* fParent;
      /// The index of this object inside the parent container
      size_t fIndex;

      ClassDef( PhotonD3PDObjectElement, 0 )

   }; // class PhotonD3PDObjectElement

   /**
    * Code generated by CodeGenerator_v2 on:
    *  host = pc-penn-d-01
    *  OS   = Linux / 2.6.18-308.8.2.el5
    *  user = stahlman
    *  time = Fri Jun 29 14:28:44 2012
    */
   class PhotonD3PDObject : public D3PDObjectBase {

   public:
      /// Constructor used when reading from a TTree
      PhotonD3PDObject( const ::Long64_t& master, const char* prefix = "ph_" );
      /// Constructor when the object is only used for writing data out
      PhotonD3PDObject( const char* prefix = "ph_" );
      /// Destructor
      ~PhotonD3PDObject();

      /// Get the currently configured prefix value
      virtual const char* GetPrefix() const;
      /// Set the prefix for the variables
      virtual void SetPrefix( const char* prefix );

      /// Connect the object to an input TTree
      virtual void ReadFrom( ::TTree* tree );
      /// Connect the object to an output TTree
      virtual void WriteTo( ::TTree* tree );

      /// Turn (selected) branches either on or off
      virtual void SetActive( ::Bool_t active = kTRUE,
                              const ::TString& pattern = ".*" );
      /// Read in all the variables that we need to write out as well
      virtual void ReadAllActive();

      /// Get the D3PD reading statistics
      virtual D3PDReadStats GetStatistics() const;

      /// Set the contents of the object according to another object
      PhotonD3PDObject& Set( const PhotonD3PDObject& parent );

      /// Clear the container. Useful when writing new branches.
      void Clear( Option_t* option = "" );
      /// Add one element to an output collection
      PhotonD3PDObject& Add( const PhotonD3PDObjectElement& el );

      /// Access a proxy class describing one element of the container
      PhotonD3PDObjectElement& operator[]( size_t index );
      /// Access a proxy class describing one element of the container (constant version)
      const PhotonD3PDObjectElement& operator[]( size_t index ) const;
      /// Add one element to an output collection
      PhotonD3PDObject& operator+=( const PhotonD3PDObjectElement& el );

      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_CaloPointing_eta] 
      VarHandle< std::vector<float,std::allocator<float> >* > CaloPointing_eta;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_CaloPointing_sigma_eta] 
      VarHandle< std::vector<float,std::allocator<float> >* > CaloPointing_sigma_eta;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_CaloPointing_sigma_zvertex] 
      VarHandle< std::vector<float,std::allocator<float> >* > CaloPointing_sigma_zvertex;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_CaloPointing_zvertex] 
      VarHandle< std::vector<float,std::allocator<float> >* > CaloPointing_zvertex;
      VarHandle< std::vector<float,std::allocator<float> >* > E;
      /// [detail 5]
      VarHandle< std::vector<float,std::allocator<float> >* > E033;
      /// [detail 7]
      VarHandle< std::vector<float,std::allocator<float> >* > E1152;
      /// [detail 6]
      VarHandle< std::vector<float,std::allocator<float> >* > E132;
      /// [detail 15]
      VarHandle< std::vector<float,std::allocator<float> >* > E233;
      /// [detail 18]
      VarHandle< std::vector<float,std::allocator<float> >* > E237;
      /// [detail 19]
      VarHandle< std::vector<float,std::allocator<float> >* > E277;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_ED_Njets] 
      VarHandle< std::vector<float,std::allocator<float> >* > ED_Njets;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_ED_median] 
      VarHandle< std::vector<float,std::allocator<float> >* > ED_median;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_ED_sigma] 
      VarHandle< std::vector<float,std::allocator<float> >* > ED_sigma;
      /// DeltaR between the offline and trigger objects.
      VarHandle< std::vector<float,std::allocator<float> >* > EF_dr;
      /// Index in trig_EF_ph_
      VarHandle< std::vector<int,std::allocator<int> >* > EF_index;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_ES0_real] 
      VarHandle< std::vector<float,std::allocator<float> >* > ES0_real;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_ES1_real] 
      VarHandle< std::vector<float,std::allocator<float> >* > ES1_real;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_ES2_real] 
      VarHandle< std::vector<float,std::allocator<float> >* > ES2_real;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_ES3_real] 
      VarHandle< std::vector<float,std::allocator<float> >* > ES3_real;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_EcellS0] 
      VarHandle< std::vector<float,std::allocator<float> >* > EcellS0;
      /// [detail 27]
      VarHandle< std::vector<float,std::allocator<float> >* > Emax2;
      /// [detail 38]
      VarHandle< std::vector<float,std::allocator<float> >* > Emins1;
      VarHandle< std::vector<float,std::allocator<float> >* > Es0;
      VarHandle< std::vector<float,std::allocator<float> >* > Es1;
      VarHandle< std::vector<float,std::allocator<float> >* > Es2;
      VarHandle< std::vector<float,std::allocator<float> >* > Es3;
      VarHandle< std::vector<float,std::allocator<float> >* > Et;
      /// [detail 285]
      VarHandle< std::vector<float,std::allocator<float> >* > Etcone15;
      /// [detail 299]pt-corrected isolation energy within DR=0.15 cone
      VarHandle< std::vector<float,std::allocator<float> >* > Etcone15_pt_corrected;
      /// [detail 1]
      VarHandle< std::vector<float,std::allocator<float> >* > Etcone20;
      /// [detail 300]pt-corrected isolation energy within DR=0.20 cone
      VarHandle< std::vector<float,std::allocator<float> >* > Etcone20_pt_corrected;
      /// [detail 286]
      VarHandle< std::vector<float,std::allocator<float> >* > Etcone25;
      /// [detail 301]pt-corrected isolation energy within DR=0.25 cone
      VarHandle< std::vector<float,std::allocator<float> >* > Etcone25_pt_corrected;
      /// [detail 2]
      VarHandle< std::vector<float,std::allocator<float> >* > Etcone30;
      /// [detail 302]pt-corrected isolation energy within DR=0.30 cone
      VarHandle< std::vector<float,std::allocator<float> >* > Etcone30_pt_corrected;
      /// [detail 287]
      VarHandle< std::vector<float,std::allocator<float> >* > Etcone35;
      /// [detail 303]pt-corrected isolation energy within DR=0.35 cone
      VarHandle< std::vector<float,std::allocator<float> >* > Etcone35_pt_corrected;
      /// [detail 3]
      VarHandle< std::vector<float,std::allocator<float> >* > Etcone40;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_Etcone40_ED_corrected] 
      VarHandle< std::vector<float,std::allocator<float> >* > Etcone40_ED_corrected;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_Etcone40_corrected] 
      VarHandle< std::vector<float,std::allocator<float> >* > Etcone40_corrected;
      /// [detail 304]pt-corrected isolation energy within DR=0.40 cone
      VarHandle< std::vector<float,std::allocator<float> >* > Etcone40_pt_corrected;
      /// [detail 0]
      VarHandle< std::vector<float,std::allocator<float> >* > Etcone45;
      /// [detail 9]
      VarHandle< std::vector<float,std::allocator<float> >* > Ethad;
      /// [detail 8]
      VarHandle< std::vector<float,std::allocator<float> >* > Ethad1;
      /// [detail 170]
      VarHandle< std::vector<float,std::allocator<float> >* > EtringnoisedR03sig2;
      /// [detail 171]
      VarHandle< std::vector<float,std::allocator<float> >* > EtringnoisedR03sig3;
      /// [detail 172]
      VarHandle< std::vector<float,std::allocator<float> >* > EtringnoisedR03sig4;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_HPV_eta] 
      VarHandle< std::vector<float,std::allocator<float> >* > HPV_eta;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_HPV_sigma_eta] 
      VarHandle< std::vector<float,std::allocator<float> >* > HPV_sigma_eta;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_HPV_sigma_zvertex] 
      VarHandle< std::vector<float,std::allocator<float> >* > HPV_sigma_zvertex;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_HPV_zvertex] 
      VarHandle< std::vector<float,std::allocator<float> >* > HPV_zvertex;
      VarHandle< std::vector<double,std::allocator<double> >* > Hmatrix;
      VarHandle< std::vector<double,std::allocator<double> >* > Hmatrix5;
      /// DeltaR between the offline and trigger objects.
      VarHandle< std::vector<float,std::allocator<float> >* > L1_dr;
      /// Index in trig_L1_emtau_
      VarHandle< std::vector<int,std::allocator<int> >* > L1_index;
      /// DeltaR between the offline and trigger objects.
      VarHandle< std::vector<float,std::allocator<float> >* > L2_dr;
      /// Index in trig_L2_ph_
      VarHandle< std::vector<int,std::allocator<int> >* > L2_index;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_NN_discriminant] 
      VarHandle< std::vector<float,std::allocator<float> >* > NN_discriminant;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_NN_passes] 
      VarHandle< std::vector<int,std::allocator<int> >* > NN_passes;
      VarHandle< std::vector<unsigned int,std::allocator<unsigned int> >* > OQ;
      VarHandle< std::vector<float,std::allocator<float> >* > Rconv;
      VarHandle< std::vector<double,std::allocator<double> >* > adaboost;
      VarHandle< std::vector<int,std::allocator<int> >* > author;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_calibHitsShowerDepth] Shower depth as defined by the calib hits cluster correction
      VarHandle< std::vector<float,std::allocator<float> >* > calibHitsShowerDepth;
      VarHandle< std::vector<float,std::allocator<float> >* > cl_E;
      VarHandle< std::vector<float,std::allocator<float> >* > cl_eta;
      VarHandle< std::vector<float,std::allocator<float> >* > cl_phi;
      VarHandle< std::vector<float,std::allocator<float> >* > cl_pt;
      /// Number of tracks for the first conversion candidate; 0 if no conversion or if there are more than two tracks.
      VarHandle< std::vector<int,std::allocator<int> >* > convFlag;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_convIP] 
      VarHandle< std::vector<float,std::allocator<float> >* > convIP;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_convIPRev] 
      VarHandle< std::vector<float,std::allocator<float> >* > convIPRev;
      /// [detail 265]
      VarHandle< std::vector<float,std::allocator<float> >* > convMatchDeltaEta1;
      /// [detail 267]
      VarHandle< std::vector<float,std::allocator<float> >* > convMatchDeltaEta2;
      /// [detail 266]
      VarHandle< std::vector<float,std::allocator<float> >* > convMatchDeltaPhi1;
      /// [detail 268]
      VarHandle< std::vector<float,std::allocator<float> >* > convMatchDeltaPhi2;
      /// [detail 72]
      VarHandle< std::vector<float,std::allocator<float> >* > convanglematch;
      /// [detail 71]
      VarHandle< std::vector<float,std::allocator<float> >* > convtrackmatch;
      VarHandle< std::vector<int,std::allocator<int> >* > convtrk1nBLHits;
      VarHandle< std::vector<int,std::allocator<int> >* > convtrk1nPixHits;
      VarHandle< std::vector<int,std::allocator<int> >* > convtrk1nSCTHits;
      VarHandle< std::vector<int,std::allocator<int> >* > convtrk1nTRTHits;
      VarHandle< std::vector<int,std::allocator<int> >* > convtrk2nBLHits;
      VarHandle< std::vector<int,std::allocator<int> >* > convtrk2nPixHits;
      VarHandle< std::vector<int,std::allocator<int> >* > convtrk2nSCTHits;
      VarHandle< std::vector<int,std::allocator<int> >* > convtrk2nTRTHits;
      VarHandle< std::vector<float,std::allocator<float> >* > convvtxchi2;
      VarHandle< std::vector<float,std::allocator<float> >* > convvtxx;
      VarHandle< std::vector<float,std::allocator<float> >* > convvtxy;
      VarHandle< std::vector<float,std::allocator<float> >* > convvtxz;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_deltaEmax2] 
      VarHandle< std::vector<float,std::allocator<float> >* > deltaEmax2;
      VarHandle< std::vector<float,std::allocator<float> >* > deltaEs;
      /// [detail 76]
      VarHandle< std::vector<float,std::allocator<float> >* > depth;
      /// Index in el_
      VarHandle< std::vector<int,std::allocator<int> >* > el_index;
      /// [detail 39]
      VarHandle< std::vector<float,std::allocator<float> >* > emaxs1;
      /// [detail 74]
      VarHandle< std::vector<float,std::allocator<float> >* > errz;
      VarHandle< std::vector<float,std::allocator<float> >* > eta;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_etacellS0] 
      VarHandle< std::vector<float,std::allocator<float> >* > etacellS0;
      /// [detail 75]
      VarHandle< std::vector<float,std::allocator<float> >* > etap;
      VarHandle< std::vector<float,std::allocator<float> >* > etas0;
      VarHandle< std::vector<float,std::allocator<float> >* > etas1;
      VarHandle< std::vector<float,std::allocator<float> >* > etas2;
      VarHandle< std::vector<float,std::allocator<float> >* > etas3;
      /// [detail 11]
      VarHandle< std::vector<float,std::allocator<float> >* > f1;
      /// [detail 13]
      VarHandle< std::vector<float,std::allocator<float> >* > f1core;
      /// [detail 12]
      VarHandle< std::vector<float,std::allocator<float> >* > f3;
      /// [detail 14]
      VarHandle< std::vector<float,std::allocator<float> >* > f3core;
      /// [detail 28]
      VarHandle< std::vector<float,std::allocator<float> >* > fside;
      VarHandle< std::vector<int,std::allocator<int> >* > goodOQ;
      VarHandle< std::vector<int,std::allocator<int> >* > hasconv;
      /// True if the first conversion candidate has 1 or 2 tracks.
      VarHandle< std::vector<int,std::allocator<int> >* > isConv;
      /// IsEM mask --- bits are set for each cut that FAILS.
      VarHandle< std::vector<unsigned int,std::allocator<unsigned int> >* > isEM;
      /// Loose IsEM mask --- bits are set for each cut that FAILS.
      VarHandle< std::vector<unsigned int,std::allocator<unsigned int> >* > isEMLoose;
      /// Medium IsEM mask --- bits are set for each cut that FAILS.
      VarHandle< std::vector<unsigned int,std::allocator<unsigned int> >* > isEMMedium;
      /// Tight IsEM mask --- bits are set for each cut that FAILS.
      VarHandle< std::vector<unsigned int,std::allocator<unsigned int> >* > isEMTight;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_isIso] Mask of isolation cuts that this object fails.  Bits are defined in egammaInterfaces/egammaIsolationMVATopToolsDefs.h,or from python, in ROOT.egammaIsolationType (in egammaInterfacesEnumsDict).
      VarHandle< std::vector<unsigned int,std::allocator<unsigned int> >* > isIso;
      VarHandle< std::vector<int,std::allocator<int> >* > isRecovered;
      VarHandle< std::vector<double,std::allocator<double> >* > isolationlikelihoodhqelectrons;
      VarHandle< std::vector<double,std::allocator<double> >* > isolationlikelihoodjets;
      VarHandle< std::vector<float,std::allocator<float> >* > jet_E;
      VarHandle< std::vector<float,std::allocator<float> >* > jet_dr;
      VarHandle< std::vector<float,std::allocator<float> >* > jet_eta;
      VarHandle< std::vector<float,std::allocator<float> >* > jet_m;
      VarHandle< std::vector<int,std::allocator<int> >* > jet_matched;
      VarHandle< std::vector<float,std::allocator<float> >* > jet_phi;
      VarHandle< std::vector<float,std::allocator<float> >* > jet_pt;
      VarHandle< std::vector<float,std::allocator<float> >* > jet_truth_E;
      VarHandle< std::vector<float,std::allocator<float> >* > jet_truth_dr;
      VarHandle< std::vector<float,std::allocator<float> >* > jet_truth_eta;
      VarHandle< std::vector<float,std::allocator<float> >* > jet_truth_m;
      VarHandle< std::vector<int,std::allocator<int> >* > jet_truth_matched;
      VarHandle< std::vector<float,std::allocator<float> >* > jet_truth_phi;
      VarHandle< std::vector<float,std::allocator<float> >* > jet_truth_pt;
      VarHandle< std::vector<double,std::allocator<double> >* > loglikelihood;
      VarHandle< std::vector<int,std::allocator<int> >* > loose;
      VarHandle< std::vector<int,std::allocator<int> >* > looseAR;
      VarHandle< std::vector<int,std::allocator<int> >* > looseARIso;
      VarHandle< std::vector<int,std::allocator<int> >* > looseIso;
      VarHandle< std::vector<float,std::allocator<float> >* > m;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_mvaptcone20] Sum of track transverse momenta within a cone of radius 0.2, as calculated by the egammaIsolationMVATopTool
      VarHandle< std::vector<float,std::allocator<float> >* > mvaptcone20;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_mvaptcone30] Sum of track transverse momenta within a cone of radius 0.3, as calculated by the egammaIsolationMVATopTool
      VarHandle< std::vector<float,std::allocator<float> >* > mvaptcone30;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_mvaptcone40] Sum of track transverse momenta within a cone of radius 0.4, as calculated by the egammaIsolationMVATopTool
      VarHandle< std::vector<float,std::allocator<float> >* > mvaptcone40;
      /// Number of ntuple rows.
      VarHandle< int > n;
      /// Number of conversion vertices.
      VarHandle< std::vector<int,std::allocator<int> >* > nConv;
      /// Number of conversion vertices with exactly two tracks.
      VarHandle< std::vector<int,std::allocator<int> >* > nDoubleTrackConv;
      /// Number of conversion vertices with exactly one track.
      VarHandle< std::vector<int,std::allocator<int> >* > nSingleTrackConv;
      VarHandle< std::vector<double,std::allocator<double> >* > neuralnet;
      /// [detail 295]
      VarHandle< std::vector<float,std::allocator<float> >* > nucone20;
      /// [detail 296]
      VarHandle< std::vector<float,std::allocator<float> >* > nucone30;
      /// [detail 297]
      VarHandle< std::vector<float,std::allocator<float> >* > nucone40;
      /// MC particle origin, from classifier tool.
      VarHandle< std::vector<int,std::allocator<int> >* > origin;
      VarHandle< std::vector<float,std::allocator<float> >* > phi;
      VarHandle< std::vector<float,std::allocator<float> >* > phis0;
      VarHandle< std::vector<float,std::allocator<float> >* > phis1;
      VarHandle< std::vector<float,std::allocator<float> >* > phis2;
      VarHandle< std::vector<float,std::allocator<float> >* > phis3;
      VarHandle< std::vector<double,std::allocator<double> >* > photonbgweight;
      VarHandle< std::vector<double,std::allocator<double> >* > photonweight;
      VarHandle< std::vector<float,std::allocator<float> >* > pt;
      VarHandle< std::vector<float,std::allocator<float> >* > pt1conv;
      VarHandle< std::vector<float,std::allocator<float> >* > pt2conv;
      /// [detail 293]
      VarHandle< std::vector<float,std::allocator<float> >* > ptcone20;
      /// [detail 241]
      VarHandle< std::vector<float,std::allocator<float> >* > ptcone30;
      /// [detail 294]
      VarHandle< std::vector<float,std::allocator<float> >* > ptcone40;
      VarHandle< std::vector<float,std::allocator<float> >* > ptconv;
      VarHandle< std::vector<float,std::allocator<float> >* > px;
      VarHandle< std::vector<float,std::allocator<float> >* > py;
      VarHandle< std::vector<float,std::allocator<float> >* > pz;
      VarHandle< std::vector<float,std::allocator<float> >* > pzconv;
      VarHandle< std::vector<float,std::allocator<float> >* > rawcl_E;
      VarHandle< std::vector<float,std::allocator<float> >* > rawcl_Es0;
      VarHandle< std::vector<float,std::allocator<float> >* > rawcl_Es1;
      VarHandle< std::vector<float,std::allocator<float> >* > rawcl_Es2;
      VarHandle< std::vector<float,std::allocator<float> >* > rawcl_Es3;
      VarHandle< std::vector<double,std::allocator<double> >* > cl_etaCalo;
      VarHandle< std::vector<double,std::allocator<double> >* > cl_phiCalo;
      VarHandle< std::vector<float,std::allocator<float> >* > rawcl_eta;
      VarHandle< std::vector<float,std::allocator<float> >* > rawcl_etas0;
      VarHandle< std::vector<float,std::allocator<float> >* > rawcl_etas1;
      VarHandle< std::vector<float,std::allocator<float> >* > rawcl_etas2;
      VarHandle< std::vector<float,std::allocator<float> >* > rawcl_etas3;
      VarHandle< std::vector<float,std::allocator<float> >* > rawcl_phi;
      VarHandle< std::vector<float,std::allocator<float> >* > rawcl_phis0;
      VarHandle< std::vector<float,std::allocator<float> >* > rawcl_phis1;
      VarHandle< std::vector<float,std::allocator<float> >* > rawcl_phis2;
      VarHandle< std::vector<float,std::allocator<float> >* > rawcl_phis3;
      VarHandle< std::vector<float,std::allocator<float> >* > rawcl_pt;
      VarHandle< std::vector<float,std::allocator<float> >* > reta;
      VarHandle< std::vector<double,std::allocator<double> >* > ringernn;
      VarHandle< std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > >* > rings_E;
      VarHandle< std::vector<float,std::allocator<float> >* > rphi;
      /// [detail 40]
      VarHandle< std::vector<float,std::allocator<float> >* > rphiallcalo;
      VarHandle< std::vector<int,std::allocator<int> >* > tight;
      VarHandle< std::vector<int,std::allocator<int> >* > tightAR;
      VarHandle< std::vector<int,std::allocator<int> >* > tightARIso;
      VarHandle< std::vector<int,std::allocator<int> >* > tightIso;
      VarHandle< std::vector<float,std::allocator<float> >* > topoEMdr;
      VarHandle< std::vector<float,std::allocator<float> >* > topoEMeta;
      VarHandle< std::vector<int,std::allocator<int> >* > topoEMmatched;
      VarHandle< std::vector<float,std::allocator<float> >* > topoEMphi;
      VarHandle< std::vector<float,std::allocator<float> >* > topoEMpt;
      /// [detail 306]
      VarHandle< std::vector<float,std::allocator<float> >* > topoEtcone20;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_topoEtcone20_corrected] 
      VarHandle< std::vector<float,std::allocator<float> >* > topoEtcone20_corrected;
      /// [detail 307]
      VarHandle< std::vector<float,std::allocator<float> >* > topoEtcone30;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_topoEtcone30_corrected] 
      VarHandle< std::vector<float,std::allocator<float> >* > topoEtcone30_corrected;
      /// [detail 308]
      VarHandle< std::vector<float,std::allocator<float> >* > topoEtcone40;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_topoEtcone40_corrected] 
      VarHandle< std::vector<float,std::allocator<float> >* > topoEtcone40_corrected;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_topoEtcone60] 
      VarHandle< std::vector<float,std::allocator<float> >* > topoEtcone60;
      VarHandle< std::vector<float,std::allocator<float> >* > topodr;
      VarHandle< std::vector<float,std::allocator<float> >* > topoeta;
      VarHandle< std::vector<int,std::allocator<int> >* > topomatched;
      VarHandle< std::vector<float,std::allocator<float> >* > topophi;
      VarHandle< std::vector<float,std::allocator<float> >* > topopt;
      VarHandle< std::vector<float,std::allocator<float> >* > truth_E;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_truth_Rconv] 
      VarHandle< std::vector<float,std::allocator<float> >* > truth_Rconv;
      VarHandle< std::vector<int,std::allocator<int> >* > truth_barcode;
      VarHandle< std::vector<float,std::allocator<float> >* > truth_deltaRRecPhoton;
      VarHandle< std::vector<float,std::allocator<float> >* > truth_eta;
      /// Index in mc_
      VarHandle< std::vector<int,std::allocator<int> >* > truth_index;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_truth_isBrem] 
      VarHandle< std::vector<int,std::allocator<int> >* > truth_isBrem;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_truth_isConv] 
      VarHandle< std::vector<int,std::allocator<int> >* > truth_isConv;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_truth_isFromHardProc] 
      VarHandle< std::vector<int,std::allocator<int> >* > truth_isFromHardProc;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_truth_isPhotonFromHardProc] 
      VarHandle< std::vector<int,std::allocator<int> >* > truth_isPhotonFromHardProc;
      VarHandle< std::vector<int,std::allocator<int> >* > truth_matched;
      VarHandle< std::vector<int,std::allocator<int> >* > truth_motherbarcode;
      VarHandle< std::vector<int,std::allocator<int> >* > truth_mothertype;
      VarHandle< std::vector<float,std::allocator<float> >* > truth_phi;
      VarHandle< std::vector<float,std::allocator<float> >* > truth_pt;
      VarHandle< std::vector<int,std::allocator<int> >* > truth_status;
      VarHandle< std::vector<int,std::allocator<int> >* > truth_type;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_truth_zconv] 
      VarHandle< std::vector<float,std::allocator<float> >* > truth_zconv;
      /// MC particle type, from classifier tool.
      VarHandle< std::vector<int,std::allocator<int> >* > type;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_Chi2] 
      VarHandle< std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > >* > vx_Chi2;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_DR1R2] 
      VarHandle< std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > >* > vx_DR1R2;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_Dcottheta] 
      VarHandle< std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > >* > vx_Dcottheta;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_Dist] 
      VarHandle< std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > >* > vx_Dist;
      /// [UserData: egammaD3PDAnalysis::_PhotonAODCollection_Dphi] 
      VarHandle< std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > >* > vx_Dphi;
      VarHandle< std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > >* > vx_E;
      VarHandle< std::vector<std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > >,std::allocator<std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > > > >* > vx_convTrk_TRTHighTHitsRatio;
      VarHandle< std::vector<std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > >,std::allocator<std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > > > >* > vx_convTrk_TRTHighTOutliersRatio;
      VarHandle< std::vector<std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > >,std::allocator<std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > > > >* > vx_convTrk_chi2;
      VarHandle< std::vector<std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > >,std::allocator<std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > > > >* > vx_convTrk_eProbabilityBrem;
      VarHandle< std::vector<std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > >,std::allocator<std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > > > >* > vx_convTrk_eProbabilityComb;
      VarHandle< std::vector<std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > >,std::allocator<std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > > > >* > vx_convTrk_eProbabilityHT;
      VarHandle< std::vector<std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > >,std::allocator<std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > > > >* > vx_convTrk_eProbabilityToT;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_expectBLayerHit;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_fitter;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_hitPattern;
      /// Number of ntuple rows.
      VarHandle< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >* > vx_convTrk_n;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nBLHits;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nBLSharedHits;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nBLayerOutliers;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nBLayerSplitHits;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nCSCEtaHits;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nCSCPhiHits;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nContribPixelLayers;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nCscEtaHoles;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nCscPhiHoles;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nGangedFlaggedFakes;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nGangedPixels;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nHits;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nHoles;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nMDTHits;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nMdtHoles;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nOutliersOnTrack;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nPixHits;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nPixHoles;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nPixSharedHits;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nPixSplitHits;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nPixelDeadSensors;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nPixelOutliers;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nPixelSpoiltHits;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nRPCEtaHits;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nRPCPhiHits;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nRpcEtaHoles;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nRpcPhiHoles;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nSCTDeadSensors;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nSCTDoubleHoles;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nSCTHits;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nSCTHoles;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nSCTOutliers;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nSCTSharedHits;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nSCTSpoiltHits;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nSiHits;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nTGCEtaHits;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nTGCPhiHits;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nTRTDeadStraws;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nTRTHighTHits;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nTRTHighTOutliers;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nTRTHits;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nTRTHoles;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nTRTOutliers;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nTRTTubeHits;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nTgcEtaHoles;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_nTgcPhiHoles;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_ndof;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_particleHypothesis;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_patternReco1;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_patternReco2;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_standardDeviationOfChi2OS;
      VarHandle< std::vector<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >,std::allocator<std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > > > >* > vx_convTrk_trackProperties;
      VarHandle< std::vector<std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > >,std::allocator<std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > > > >* > vx_convTrk_weight;
      VarHandle< std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > >* > vx_m;
      /// Number of ntuple rows.
      VarHandle< std::vector<int,std::allocator<int> >* > vx_n;
      VarHandle< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >* > vx_nTracks;
      VarHandle< std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > >* > vx_px;
      VarHandle< std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > >* > vx_py;
      VarHandle< std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > >* > vx_pz;
      VarHandle< std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > >* > vx_sumPt;
      VarHandle< std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > >* > vx_x;
      VarHandle< std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > >* > vx_y;
      VarHandle< std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > >* > vx_z;
      /// [detail 25]
      VarHandle< std::vector<float,std::allocator<float> >* > weta2;
      /// [detail 24]
      VarHandle< std::vector<float,std::allocator<float> >* > ws3;
      /// [detail 37]
      VarHandle< std::vector<float,std::allocator<float> >* > wstot;
      VarHandle< std::vector<float,std::allocator<float> >* > zconv;
      /// [detail 73]
      VarHandle< std::vector<float,std::allocator<float> >* > zvertex;

   private:
      mutable std::vector< PhotonD3PDObjectElement* > fProxies; ///< Internal list of proxy objects
      std::map< ::TString, VarHandleBase* > fHandles; ///< Book-keeper of the VarHandle members
      const ::Bool_t fFromInput; ///< Flag specifying if object is used for D3PD reading
      ::TString fPrefix; ///< Prefix to the branch names

      ClassDef( PhotonD3PDObject, 0 )

   }; // class PhotonD3PDObject

} // namespace D3PDReader

#endif // D3PDREADER_PhotonD3PDObject_H
