// Dear emacs, this is -*- c++ -*-
// -------------------------------------------------------------
//             Code produced by D3PDMakerReader
//
//  author: Attila Krasznahorkay <Attila.Krasznahorkay@cern.ch>
// -------------------------------------------------------------
#ifndef D3PDREADER_TauD3PDObject_H
#define D3PDREADER_TauD3PDObject_H

#include <map>
#include <vector>
using std::vector;

#include <TObject.h>
#include <TString.h>

#include "D3PDObjectBase.h"
#include "D3PDReadStats.h"
#include "VarHandle.h"
#include "VarProxy.h"

class TTree;

namespace D3PDReader {

   // Forward declaration(s):
   class TauD3PDObject;

   /**
    * Code generated by CodeGenerator_v2 on:
    *  host = pc-penn-d-01
    *  OS   = Linux / 2.6.18-308.8.2.el5
    *  user = stahlman
    *  time = Fri Jun 29 14:28:44 2012
    */
   class TauD3PDObjectElement : public TObject {

      friend class TauD3PDObject;

   protected:
      /// Constructor only visible to TauD3PDObject
      TauD3PDObjectElement( size_t index, const TauD3PDObject& parent );

   public:
      /// Copy constructor
      TauD3PDObjectElement( const TauD3PDObjectElement& parent );

      /// Parent object of this proxy object
      const TauD3PDObject* GetParent() const;
      /// Index of the object inside its container
      size_t GetIndex() const;

      VarProxy< float > BDTEleScore;
      VarProxy< float > BDTJetScore;
      VarProxy< float > EF_E;
      VarProxy< float > EF_Et;
      /// DeltaR between the offline and trigger objects.
      VarProxy< float > EF_dr;
      VarProxy< float > EF_eta;
      VarProxy< int > EF_matched;
      VarProxy< float > EF_phi;
      VarProxy< float > EF_pt;
      VarProxy< float > EM_TES_scale;
      VarProxy< int > EleBDTLoose;
      VarProxy< int > EleBDTMedium;
      VarProxy< int > EleBDTTight;
      VarProxy< float > Et;
      VarProxy< int > JetBDTSigLoose;
      VarProxy< int > JetBDTSigMedium;
      VarProxy< int > JetBDTSigTight;
      VarProxy< float > L1_Et;
      /// DeltaR between the offline and trigger objects.
      VarProxy< float > L1_dr;
      VarProxy< float > L1_eta;
      VarProxy< int > L1_matched;
      VarProxy< float > L1_phi;
      VarProxy< float > L1_pt;
      VarProxy< float > L2_E;
      VarProxy< float > L2_Et;
      /// DeltaR between the offline and trigger objects.
      VarProxy< float > L2_dr;
      VarProxy< float > L2_eta;
      VarProxy< int > L2_matched;
      VarProxy< float > L2_phi;
      VarProxy< float > L2_pt;
      VarProxy< float > LC_TES_precalib;
      VarProxy< int > RoIWord;
      VarProxy< float > SafeLikelihood;
      VarProxy< float > TRTHTOverLT_LeadTrk;
      VarProxy< int > author;
      VarProxy< float > calcVars_ChPiEMEOverCaloEME;
      VarProxy< float > calcVars_EMFractionAtEMScale;
      VarProxy< float > calcVars_EMPOverTrkSysP;
      VarProxy< float > calcVars_PSSFraction;
      VarProxy< float > calcVars_calRadius;
      VarProxy< float > calcVars_corrCentFrac;
      VarProxy< float > calcVars_corrFTrk;
      VarProxy< float > calcVars_drMin;
      VarProxy< float > calcVars_etEM_EMScale_Pt3Trks;
      VarProxy< float > calcVars_etHad_EMScale_Pt3Trks;
      VarProxy< float > calcVars_interAxis_eta;
      VarProxy< float > calcVars_interAxis_phi;
      VarProxy< float > calcVars_ipSigLeadLooseTrk;
      VarProxy< float > calcVars_pi0BDTPrimaryScore;
      VarProxy< float > calcVars_pi0BDTSecondaryScore;
      VarProxy< float > calcVars_trackIso;
      VarProxy< float > cellBasedEnergyRing1;
      VarProxy< float > cellBasedEnergyRing2;
      VarProxy< float > cellBasedEnergyRing3;
      VarProxy< float > cellBasedEnergyRing4;
      VarProxy< float > cellBasedEnergyRing5;
      VarProxy< float > cellBasedEnergyRing6;
      VarProxy< float > cellBasedEnergyRing7;
      VarProxy< float > charge;
      VarProxy< float > chrgLooseTrk;
      VarProxy< float > effTopoInvMass;
      VarProxy< float > effTopoMeanDeltaR;
      VarProxy< float > ele_E237E277;
      VarProxy< float > ele_ECALFirstFraction;
      VarProxy< float > ele_PresamplerFraction;
      VarProxy< int > electronVetoLoose;
      VarProxy< int > electronVetoMedium;
      VarProxy< int > electronVetoTight;
      VarProxy< float > etEflow;
      VarProxy< float > etOverPtLeadLooseTrk;
      VarProxy< float > etOverPtLeadTrk;
      VarProxy< float > eta;
      VarProxy< float > ipSigLeadLooseTrk;
      VarProxy< float > ipSigLeadTrk;
      VarProxy< float > ipZ0SinThetaSigLeadTrk;
      VarProxy< float > leadLooseTrkPt;
      VarProxy< float > leadTrack_eta;
      VarProxy< float > leadTrack_phi;
      VarProxy< float > leadTrkPt;
      VarProxy< float > likelihood;
      VarProxy< float > m;
      VarProxy< float > mEflow;
      VarProxy< float > massTrkSys;
      VarProxy< int > muonVeto;
      VarProxy< int > nLooseConvTrk;
      VarProxy< int > nLooseTrk;
      VarProxy< int > nOtherTrk;
      VarProxy< int > nPi0;
      VarProxy< int > nProng;
      VarProxy< int > nProngLoose;
      VarProxy< float > numCells;
      VarProxy< float > numEffTopoClusters;
      VarProxy< int > numTopoClusters;
      VarProxy< int > numTrack;
      /// Number of ntuple rows.
      VarProxy< int > otherTrk_atTJVA_n;
      /// Number of ntuple rows.
      VarProxy< int > otherTrk_n;
      VarProxy< float > phi;
      VarProxy< float > pt;
      VarProxy< float > seedCalo_EMRadius;
      VarProxy< float > seedCalo_caloIso;
      VarProxy< float > seedCalo_caloIsoCorrected;
      VarProxy< float > seedCalo_centFrac;
      VarProxy< float > seedCalo_dRmax;
      VarProxy< float > seedCalo_etEMAtEMScale;
      VarProxy< float > seedCalo_etEMCalib;
      VarProxy< float > seedCalo_etHadAtEMScale;
      VarProxy< float > seedCalo_etHadCalib;
      VarProxy< float > seedCalo_eta;
      VarProxy< float > seedCalo_hadRadius;
      VarProxy< float > seedCalo_isolFrac;
      VarProxy< float > seedCalo_lead2ClusterEOverAllClusterE;
      VarProxy< float > seedCalo_lead3ClusterEOverAllClusterE;
      VarProxy< float > seedCalo_nIsolLooseTrk;
      VarProxy< int > seedCalo_nStrip;
      VarProxy< int > seedCalo_nWideTrk;
      VarProxy< int > seedCalo_numTrack;
      VarProxy< float > seedCalo_phi;
      VarProxy< float > seedCalo_stripWidth2;
      /// Number of ntuple rows.
      VarProxy< int > seedCalo_track_n;
      VarProxy< float > seedCalo_trkAvgDist;
      VarProxy< float > seedCalo_trkRmsDist;
      /// Number of ntuple rows.
      VarProxy< int > seedCalo_wideTrk_atTJVA_n;
      /// Number of ntuple rows.
      VarProxy< int > seedCalo_wideTrk_n;
      VarProxy< float > seedTrk_EMRadius;
      VarProxy< float > seedTrk_etChrgEM;
      VarProxy< float > seedTrk_etChrgHad;
      VarProxy< float > seedTrk_etChrgHadOverSumTrkPt;
      VarProxy< float > seedTrk_etEMAtEMScale;
      VarProxy< float > seedTrk_etEMCL;
      VarProxy< float > seedTrk_etHadAtEMScale;
      VarProxy< float > seedTrk_etIsolEM;
      VarProxy< float > seedTrk_etIsolHad;
      VarProxy< float > seedTrk_etNeuEM;
      VarProxy< float > seedTrk_etResNeuEM;
      VarProxy< float > seedTrk_hadLeakEt;
      VarProxy< float > seedTrk_isolFrac;
      VarProxy< float > seedTrk_isolFracWide;
      VarProxy< int > seedTrk_nIsolTrk;
      VarProxy< int > seedTrk_nOtherCoreTrk;
      VarProxy< int > seedTrk_nStrip;
      VarProxy< float > seedTrk_secMaxStripEt;
      VarProxy< float > seedTrk_stripWidth2;
      VarProxy< float > seedTrk_sumEMCellEtOverLeadTrkPt;
      VarProxy< int > tauLlhLoose;
      VarProxy< int > tauLlhMedium;
      VarProxy< int > tauLlhTight;
      VarProxy< float > topoInvMass;
      VarProxy< float > topoMeanDeltaR;
      VarProxy< float > trFlightPathSig;
      /// Number of ntuple rows.
      VarProxy< int > track_atTJVA_n;
      /// Number of ntuple rows.
      VarProxy< int > track_n;
      VarProxy< float > trkWidth2;

   private:
      /// Reference to the parent of this object
      const TauD3PDObject* fParent;
      /// The index of this object inside the parent container
      size_t fIndex;

      ClassDef( TauD3PDObjectElement, 0 )

   }; // class TauD3PDObjectElement

   /**
    * Code generated by CodeGenerator_v2 on:
    *  host = pc-penn-d-01
    *  OS   = Linux / 2.6.18-308.8.2.el5
    *  user = stahlman
    *  time = Fri Jun 29 14:28:44 2012
    */
   class TauD3PDObject : public D3PDObjectBase {

   public:
      /// Constructor used when reading from a TTree
      TauD3PDObject( const ::Long64_t& master, const char* prefix = "tau_" );
      /// Constructor when the object is only used for writing data out
      TauD3PDObject( const char* prefix = "tau_" );
      /// Destructor
      ~TauD3PDObject();

      /// Get the currently configured prefix value
      virtual const char* GetPrefix() const;
      /// Set the prefix for the variables
      virtual void SetPrefix( const char* prefix );

      /// Connect the object to an input TTree
      virtual void ReadFrom( ::TTree* tree );
      /// Connect the object to an output TTree
      virtual void WriteTo( ::TTree* tree );

      /// Turn (selected) branches either on or off
      virtual void SetActive( ::Bool_t active = kTRUE,
                              const ::TString& pattern = ".*" );
      /// Read in all the variables that we need to write out as well
      virtual void ReadAllActive();

      /// Get the D3PD reading statistics
      virtual D3PDReadStats GetStatistics() const;

      /// Set the contents of the object according to another object
      TauD3PDObject& Set( const TauD3PDObject& parent );

      /// Clear the container. Useful when writing new branches.
      void Clear( Option_t* option = "" );
      /// Add one element to an output collection
      TauD3PDObject& Add( const TauD3PDObjectElement& el );

      /// Access a proxy class describing one element of the container
      TauD3PDObjectElement& operator[]( size_t index );
      /// Access a proxy class describing one element of the container (constant version)
      const TauD3PDObjectElement& operator[]( size_t index ) const;
      /// Add one element to an output collection
      TauD3PDObject& operator+=( const TauD3PDObjectElement& el );

      VarHandle< std::vector<float,std::allocator<float> >* > BDTEleScore;
      VarHandle< std::vector<float,std::allocator<float> >* > BDTJetScore;
      VarHandle< std::vector<float,std::allocator<float> >* > EF_E;
      VarHandle< std::vector<float,std::allocator<float> >* > EF_Et;
      /// DeltaR between the offline and trigger objects.
      VarHandle< std::vector<float,std::allocator<float> >* > EF_dr;
      VarHandle< std::vector<float,std::allocator<float> >* > EF_eta;
      VarHandle< std::vector<int,std::allocator<int> >* > EF_matched;
      VarHandle< std::vector<float,std::allocator<float> >* > EF_phi;
      VarHandle< std::vector<float,std::allocator<float> >* > EF_pt;
      VarHandle< std::vector<float,std::allocator<float> >* > EM_TES_scale;
      VarHandle< std::vector<int,std::allocator<int> >* > EleBDTLoose;
      VarHandle< std::vector<int,std::allocator<int> >* > EleBDTMedium;
      VarHandle< std::vector<int,std::allocator<int> >* > EleBDTTight;
      VarHandle< std::vector<float,std::allocator<float> >* > Et;
      VarHandle< std::vector<int,std::allocator<int> >* > JetBDTSigLoose;
      VarHandle< std::vector<int,std::allocator<int> >* > JetBDTSigMedium;
      VarHandle< std::vector<int,std::allocator<int> >* > JetBDTSigTight;
      VarHandle< std::vector<float,std::allocator<float> >* > L1_Et;
      /// DeltaR between the offline and trigger objects.
      VarHandle< std::vector<float,std::allocator<float> >* > L1_dr;
      VarHandle< std::vector<float,std::allocator<float> >* > L1_eta;
      VarHandle< std::vector<int,std::allocator<int> >* > L1_matched;
      VarHandle< std::vector<float,std::allocator<float> >* > L1_phi;
      VarHandle< std::vector<float,std::allocator<float> >* > L1_pt;
      VarHandle< std::vector<float,std::allocator<float> >* > L2_E;
      VarHandle< std::vector<float,std::allocator<float> >* > L2_Et;
      /// DeltaR between the offline and trigger objects.
      VarHandle< std::vector<float,std::allocator<float> >* > L2_dr;
      VarHandle< std::vector<float,std::allocator<float> >* > L2_eta;
      VarHandle< std::vector<int,std::allocator<int> >* > L2_matched;
      VarHandle< std::vector<float,std::allocator<float> >* > L2_phi;
      VarHandle< std::vector<float,std::allocator<float> >* > L2_pt;
      VarHandle< std::vector<float,std::allocator<float> >* > LC_TES_precalib;
      VarHandle< std::vector<int,std::allocator<int> >* > RoIWord;
      VarHandle< std::vector<float,std::allocator<float> >* > SafeLikelihood;
      VarHandle< std::vector<float,std::allocator<float> >* > TRTHTOverLT_LeadTrk;
      VarHandle< std::vector<int,std::allocator<int> >* > author;
      VarHandle< std::vector<float,std::allocator<float> >* > calcVars_ChPiEMEOverCaloEME;
      VarHandle< std::vector<float,std::allocator<float> >* > calcVars_EMFractionAtEMScale;
      VarHandle< std::vector<float,std::allocator<float> >* > calcVars_EMPOverTrkSysP;
      VarHandle< std::vector<float,std::allocator<float> >* > calcVars_PSSFraction;
      VarHandle< std::vector<float,std::allocator<float> >* > calcVars_calRadius;
      VarHandle< std::vector<float,std::allocator<float> >* > calcVars_corrCentFrac;
      VarHandle< std::vector<float,std::allocator<float> >* > calcVars_corrFTrk;
      VarHandle< std::vector<float,std::allocator<float> >* > calcVars_drMin;
      VarHandle< std::vector<float,std::allocator<float> >* > calcVars_etEM_EMScale_Pt3Trks;
      VarHandle< std::vector<float,std::allocator<float> >* > calcVars_etHad_EMScale_Pt3Trks;
      VarHandle< std::vector<float,std::allocator<float> >* > calcVars_interAxis_eta;
      VarHandle< std::vector<float,std::allocator<float> >* > calcVars_interAxis_phi;
      VarHandle< std::vector<float,std::allocator<float> >* > calcVars_ipSigLeadLooseTrk;
      VarHandle< std::vector<float,std::allocator<float> >* > calcVars_pi0BDTPrimaryScore;
      VarHandle< std::vector<float,std::allocator<float> >* > calcVars_pi0BDTSecondaryScore;
      VarHandle< std::vector<float,std::allocator<float> >* > calcVars_trackIso;
      VarHandle< std::vector<float,std::allocator<float> >* > cellBasedEnergyRing1;
      VarHandle< std::vector<float,std::allocator<float> >* > cellBasedEnergyRing2;
      VarHandle< std::vector<float,std::allocator<float> >* > cellBasedEnergyRing3;
      VarHandle< std::vector<float,std::allocator<float> >* > cellBasedEnergyRing4;
      VarHandle< std::vector<float,std::allocator<float> >* > cellBasedEnergyRing5;
      VarHandle< std::vector<float,std::allocator<float> >* > cellBasedEnergyRing6;
      VarHandle< std::vector<float,std::allocator<float> >* > cellBasedEnergyRing7;
      VarHandle< std::vector<float,std::allocator<float> >* > charge;
      VarHandle< std::vector<float,std::allocator<float> >* > chrgLooseTrk;
      VarHandle< std::vector<float,std::allocator<float> >* > effTopoInvMass;
      VarHandle< std::vector<float,std::allocator<float> >* > effTopoMeanDeltaR;
      VarHandle< std::vector<float,std::allocator<float> >* > ele_E237E277;
      VarHandle< std::vector<float,std::allocator<float> >* > ele_ECALFirstFraction;
      VarHandle< std::vector<float,std::allocator<float> >* > ele_PresamplerFraction;
      VarHandle< std::vector<int,std::allocator<int> >* > electronVetoLoose;
      VarHandle< std::vector<int,std::allocator<int> >* > electronVetoMedium;
      VarHandle< std::vector<int,std::allocator<int> >* > electronVetoTight;
      VarHandle< std::vector<float,std::allocator<float> >* > etEflow;
      VarHandle< std::vector<float,std::allocator<float> >* > etOverPtLeadLooseTrk;
      VarHandle< std::vector<float,std::allocator<float> >* > etOverPtLeadTrk;
      VarHandle< std::vector<float,std::allocator<float> >* > eta;
      VarHandle< std::vector<float,std::allocator<float> >* > ipSigLeadLooseTrk;
      VarHandle< std::vector<float,std::allocator<float> >* > ipSigLeadTrk;
      VarHandle< std::vector<float,std::allocator<float> >* > ipZ0SinThetaSigLeadTrk;
      VarHandle< std::vector<float,std::allocator<float> >* > leadLooseTrkPt;
      VarHandle< std::vector<float,std::allocator<float> >* > leadTrack_eta;
      VarHandle< std::vector<float,std::allocator<float> >* > leadTrack_phi;
      VarHandle< std::vector<float,std::allocator<float> >* > leadTrkPt;
      VarHandle< std::vector<float,std::allocator<float> >* > likelihood;
      VarHandle< std::vector<float,std::allocator<float> >* > m;
      VarHandle< std::vector<float,std::allocator<float> >* > mEflow;
      VarHandle< std::vector<float,std::allocator<float> >* > massTrkSys;
      VarHandle< std::vector<int,std::allocator<int> >* > muonVeto;
      /// Number of ntuple rows.
      VarHandle< int > n;
      VarHandle< std::vector<int,std::allocator<int> >* > nLooseConvTrk;
      VarHandle< std::vector<int,std::allocator<int> >* > nLooseTrk;
      VarHandle< std::vector<int,std::allocator<int> >* > nOtherTrk;
      VarHandle< std::vector<int,std::allocator<int> >* > nPi0;
      VarHandle< std::vector<int,std::allocator<int> >* > nProng;
      VarHandle< std::vector<int,std::allocator<int> >* > nProngLoose;
      VarHandle< std::vector<float,std::allocator<float> >* > numCells;
      VarHandle< std::vector<float,std::allocator<float> >* > numEffTopoClusters;
      VarHandle< std::vector<int,std::allocator<int> >* > numTopoClusters;
      VarHandle< std::vector<int,std::allocator<int> >* > numTrack;
      /// Number of ntuple rows.
      VarHandle< std::vector<int,std::allocator<int> >* > otherTrk_atTJVA_n;
      /// Number of ntuple rows.
      VarHandle< std::vector<int,std::allocator<int> >* > otherTrk_n;
      VarHandle< std::vector<float,std::allocator<float> >* > phi;
      VarHandle< std::vector<float,std::allocator<float> >* > pt;
      VarHandle< std::vector<float,std::allocator<float> >* > seedCalo_EMRadius;
      VarHandle< std::vector<float,std::allocator<float> >* > seedCalo_caloIso;
      VarHandle< std::vector<float,std::allocator<float> >* > seedCalo_caloIsoCorrected;
      VarHandle< std::vector<float,std::allocator<float> >* > seedCalo_centFrac;
      VarHandle< std::vector<float,std::allocator<float> >* > seedCalo_dRmax;
      VarHandle< std::vector<float,std::allocator<float> >* > seedCalo_etEMAtEMScale;
      VarHandle< std::vector<float,std::allocator<float> >* > seedCalo_etEMCalib;
      VarHandle< std::vector<float,std::allocator<float> >* > seedCalo_etHadAtEMScale;
      VarHandle< std::vector<float,std::allocator<float> >* > seedCalo_etHadCalib;
      VarHandle< std::vector<float,std::allocator<float> >* > seedCalo_eta;
      VarHandle< std::vector<float,std::allocator<float> >* > seedCalo_hadRadius;
      VarHandle< std::vector<float,std::allocator<float> >* > seedCalo_isolFrac;
      VarHandle< std::vector<float,std::allocator<float> >* > seedCalo_lead2ClusterEOverAllClusterE;
      VarHandle< std::vector<float,std::allocator<float> >* > seedCalo_lead3ClusterEOverAllClusterE;
      VarHandle< std::vector<float,std::allocator<float> >* > seedCalo_nIsolLooseTrk;
      VarHandle< std::vector<int,std::allocator<int> >* > seedCalo_nStrip;
      VarHandle< std::vector<int,std::allocator<int> >* > seedCalo_nWideTrk;
      VarHandle< std::vector<int,std::allocator<int> >* > seedCalo_numTrack;
      VarHandle< std::vector<float,std::allocator<float> >* > seedCalo_phi;
      VarHandle< std::vector<float,std::allocator<float> >* > seedCalo_stripWidth2;
      /// Number of ntuple rows.
      VarHandle< std::vector<int,std::allocator<int> >* > seedCalo_track_n;
      VarHandle< std::vector<float,std::allocator<float> >* > seedCalo_trkAvgDist;
      VarHandle< std::vector<float,std::allocator<float> >* > seedCalo_trkRmsDist;
      /// Number of ntuple rows.
      VarHandle< std::vector<int,std::allocator<int> >* > seedCalo_wideTrk_atTJVA_n;
      /// Number of ntuple rows.
      VarHandle< std::vector<int,std::allocator<int> >* > seedCalo_wideTrk_n;
      VarHandle< std::vector<float,std::allocator<float> >* > seedTrk_EMRadius;
      VarHandle< std::vector<float,std::allocator<float> >* > seedTrk_etChrgEM;
      VarHandle< std::vector<float,std::allocator<float> >* > seedTrk_etChrgHad;
      VarHandle< std::vector<float,std::allocator<float> >* > seedTrk_etChrgHadOverSumTrkPt;
      VarHandle< std::vector<float,std::allocator<float> >* > seedTrk_etEMAtEMScale;
      VarHandle< std::vector<float,std::allocator<float> >* > seedTrk_etEMCL;
      VarHandle< std::vector<float,std::allocator<float> >* > seedTrk_etHadAtEMScale;
      VarHandle< std::vector<float,std::allocator<float> >* > seedTrk_etIsolEM;
      VarHandle< std::vector<float,std::allocator<float> >* > seedTrk_etIsolHad;
      VarHandle< std::vector<float,std::allocator<float> >* > seedTrk_etNeuEM;
      VarHandle< std::vector<float,std::allocator<float> >* > seedTrk_etResNeuEM;
      VarHandle< std::vector<float,std::allocator<float> >* > seedTrk_hadLeakEt;
      VarHandle< std::vector<float,std::allocator<float> >* > seedTrk_isolFrac;
      VarHandle< std::vector<float,std::allocator<float> >* > seedTrk_isolFracWide;
      VarHandle< std::vector<int,std::allocator<int> >* > seedTrk_nIsolTrk;
      VarHandle< std::vector<int,std::allocator<int> >* > seedTrk_nOtherCoreTrk;
      VarHandle< std::vector<int,std::allocator<int> >* > seedTrk_nStrip;
      VarHandle< std::vector<float,std::allocator<float> >* > seedTrk_secMaxStripEt;
      VarHandle< std::vector<float,std::allocator<float> >* > seedTrk_stripWidth2;
      VarHandle< std::vector<float,std::allocator<float> >* > seedTrk_sumEMCellEtOverLeadTrkPt;
      VarHandle< std::vector<int,std::allocator<int> >* > tauLlhLoose;
      VarHandle< std::vector<int,std::allocator<int> >* > tauLlhMedium;
      VarHandle< std::vector<int,std::allocator<int> >* > tauLlhTight;
      VarHandle< std::vector<float,std::allocator<float> >* > topoInvMass;
      VarHandle< std::vector<float,std::allocator<float> >* > topoMeanDeltaR;
      VarHandle< std::vector<float,std::allocator<float> >* > trFlightPathSig;
      /// Number of ntuple rows.
      VarHandle< std::vector<int,std::allocator<int> >* > track_atTJVA_n;
      /// Number of ntuple rows.
      VarHandle< std::vector<int,std::allocator<int> >* > track_n;
      VarHandle< std::vector<float,std::allocator<float> >* > trkWidth2;

   private:
      mutable std::vector< TauD3PDObjectElement* > fProxies; ///< Internal list of proxy objects
      std::map< ::TString, VarHandleBase* > fHandles; ///< Book-keeper of the VarHandle members
      const ::Bool_t fFromInput; ///< Flag specifying if object is used for D3PD reading
      ::TString fPrefix; ///< Prefix to the branch names

      ClassDef( TauD3PDObject, 0 )

   }; // class TauD3PDObject

} // namespace D3PDReader

#endif // D3PDREADER_TauD3PDObject_H
