// Dear emacs, this is -*- c++ -*-
// -------------------------------------------------------------
//             Code produced by D3PDMakerReader
//
//  author: Attila Krasznahorkay <Attila.Krasznahorkay@cern.ch>
// -------------------------------------------------------------
#ifndef D3PDREADER_TruthParticleD3PDObject_H
#define D3PDREADER_TruthParticleD3PDObject_H

#include <map>
#include <vector>
using std::vector;

#include <TObject.h>
#include <TString.h>

#include "D3PDObjectBase.h"
#include "D3PDReadStats.h"
#include "VarHandle.h"
#include "VarProxy.h"

class TTree;

namespace D3PDReader {

   // Forward declaration(s):
   class TruthParticleD3PDObject;

   /**
    * Code generated by CodeGenerator_v2 on:
    *  host = pc-penn-d-01
    *  OS   = Linux / 2.6.18-308.8.2.el5
    *  user = stahlman
    *  time = Fri Jun 29 14:28:44 2012
    */
   class TruthParticleD3PDObjectElement : public TObject {

      friend class TruthParticleD3PDObject;

   protected:
      /// Constructor only visible to TruthParticleD3PDObject
      TruthParticleD3PDObjectElement( size_t index, const TruthParticleD3PDObject& parent );

   public:
      /// Copy constructor
      TruthParticleD3PDObjectElement( const TruthParticleD3PDObjectElement& parent );

      /// Parent object of this proxy object
      const TruthParticleD3PDObject* GetParent() const;
      /// Index of the object inside its container
      size_t GetIndex() const;

      VarProxy< int > barcode;
      VarProxy< float > charge;
      /// Index in mc_
      VarProxy< std::vector<int,std::allocator<int> > > child_index;
      VarProxy< std::vector<int,std::allocator<int> > > children;
      VarProxy< float > eta;
      VarProxy< float > m;
      /// Index in mc_
      VarProxy< std::vector<int,std::allocator<int> > > parent_index;
      VarProxy< std::vector<int,std::allocator<int> > > parents;
      VarProxy< int > pdgId;
      VarProxy< float > phi;
      VarProxy< float > pt;
      VarProxy< int > status;
      /// Vertex barcode
      VarProxy< int > vx_barcode;
      /// Vertex x position
      VarProxy< float > vx_x;
      /// Vertex y position
      VarProxy< float > vx_y;
      /// Vertex z position
      VarProxy< float > vx_z;

   private:
      /// Reference to the parent of this object
      const TruthParticleD3PDObject* fParent;
      /// The index of this object inside the parent container
      size_t fIndex;

      ClassDef( TruthParticleD3PDObjectElement, 0 )

   }; // class TruthParticleD3PDObjectElement

   /**
    * Code generated by CodeGenerator_v2 on:
    *  host = pc-penn-d-01
    *  OS   = Linux / 2.6.18-308.8.2.el5
    *  user = stahlman
    *  time = Fri Jun 29 14:28:44 2012
    */
   class TruthParticleD3PDObject : public D3PDObjectBase {

   public:
      /// Constructor used when reading from a TTree
      TruthParticleD3PDObject( const ::Long64_t& master, const char* prefix = "mc_" );
      /// Constructor when the object is only used for writing data out
      TruthParticleD3PDObject( const char* prefix = "mc_" );
      /// Destructor
      ~TruthParticleD3PDObject();

      /// Get the currently configured prefix value
      virtual const char* GetPrefix() const;
      /// Set the prefix for the variables
      virtual void SetPrefix( const char* prefix );

      /// Connect the object to an input TTree
      virtual void ReadFrom( ::TTree* tree );
      /// Connect the object to an output TTree
      virtual void WriteTo( ::TTree* tree );

      /// Turn (selected) branches either on or off
      virtual void SetActive( ::Bool_t active = kTRUE,
                              const ::TString& pattern = ".*" );
      /// Read in all the variables that we need to write out as well
      virtual void ReadAllActive();

      /// Get the D3PD reading statistics
      virtual D3PDReadStats GetStatistics() const;

      /// Set the contents of the object according to another object
      TruthParticleD3PDObject& Set( const TruthParticleD3PDObject& parent );

      /// Clear the container. Useful when writing new branches.
      void Clear( Option_t* option = "" );
      /// Add one element to an output collection
      TruthParticleD3PDObject& Add( const TruthParticleD3PDObjectElement& el );

      /// Access a proxy class describing one element of the container
      TruthParticleD3PDObjectElement& operator[]( size_t index );
      /// Access a proxy class describing one element of the container (constant version)
      const TruthParticleD3PDObjectElement& operator[]( size_t index ) const;
      /// Add one element to an output collection
      TruthParticleD3PDObject& operator+=( const TruthParticleD3PDObjectElement& el );

      VarHandle< std::vector<int,std::allocator<int> >* > barcode;
      VarHandle< std::vector<float,std::allocator<float> >* > charge;
      /// Index in mc_
      VarHandle< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >* > child_index;
      VarHandle< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >* > children;
      VarHandle< std::vector<float,std::allocator<float> >* > eta;
      VarHandle< std::vector<float,std::allocator<float> >* > m;
      /// Number of ntuple rows.
      VarHandle< int > n;
      /// Index in mc_
      VarHandle< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >* > parent_index;
      VarHandle< std::vector<std::vector<int,std::allocator<int> >,std::allocator<std::vector<int,std::allocator<int> > > >* > parents;
      VarHandle< std::vector<int,std::allocator<int> >* > pdgId;
      VarHandle< std::vector<float,std::allocator<float> >* > phi;
      VarHandle< std::vector<float,std::allocator<float> >* > pt;
      VarHandle< std::vector<int,std::allocator<int> >* > status;
      /// Vertex barcode
      VarHandle< std::vector<int,std::allocator<int> >* > vx_barcode;
      /// Vertex x position
      VarHandle< std::vector<float,std::allocator<float> >* > vx_x;
      /// Vertex y position
      VarHandle< std::vector<float,std::allocator<float> >* > vx_y;
      /// Vertex z position
      VarHandle< std::vector<float,std::allocator<float> >* > vx_z;

   private:
      mutable std::vector< TruthParticleD3PDObjectElement* > fProxies; ///< Internal list of proxy objects
      std::map< ::TString, VarHandleBase* > fHandles; ///< Book-keeper of the VarHandle members
      const ::Bool_t fFromInput; ///< Flag specifying if object is used for D3PD reading
      ::TString fPrefix; ///< Prefix to the branch names

      ClassDef( TruthParticleD3PDObject, 0 )

   }; // class TruthParticleD3PDObject

} // namespace D3PDReader

#endif // D3PDREADER_TruthParticleD3PDObject_H
