# Package information
LIBRARY = ZZMassResolution
OBJDIR  = obj
DEPDIR  = $(OBJDIR)/dep
SRCDIR  = src
INCDIR  = include

INCLUDES += -I../RootCore/RootCore/include
INCLUDES += -I../D3PDObjects/include
INCLUDES += -I../AtlasSFrameUtils/include
INCLUDES += -I../CommonTools/include
INCLUDES += -I../ZZSelection/include

# Include the generic compilation rules
include $(SFRAME_DIR)/Makefile.common
